### ISSUE TITLE
MD5 vs FIPS encryption incomatibility + workaround

### ISSUE THREAD

**Issue by wladerer** [Quantum-Accelerators/quacc#2257]
### FIPS system error

Hi everyone, 

I didn't submit this as a bug because I don't believe this is the responsibility of quacc to address this. I am only putting this here for future users. 

When running the EMT tutorial, I received the following error:

```
Traceback (most recent call last):
  File "/p/work1/wladerer/quacctest/emt.py", line 8, in <module>
    result = relax_job(atoms)
             ^^^^^^^^^^^^^^^^
  File "/p/home/wladerer/.pyenv/versions/3.11.7/lib/python3.11/site-packages/quacc/recipes/emt/core.py", line 97, in relax_job
    return summarize_opt_run(dyn, additional_fields={"name": "EMT Relax"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/home/wladerer/.pyenv/versions/3.11.7/lib/python3.11/site-packages/quacc/schemas/ase.py", line 186, in summarize_opt_run
    base_task_doc = summarize_run(
                    ^^^^^^^^^^^^^^
  File "/p/home/wladerer/.pyenv/versions/3.11.7/lib/python3.11/site-packages/quacc/schemas/ase.py", line 105, in summarize_run
    atoms_to_store = prep_next_run(final_atoms, move_magmoms=move_magmoms)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/home/wladerer/.pyenv/versions/3.11.7/lib/python3.11/site-packages/quacc/schemas/prep.py", line 60, in prep_next_run
    atoms.info["_id"] = get_atoms_id(atoms)
                        ^^^^^^^^^^^^^^^^^^^
  File "/p/home/wladerer/.pyenv/versions/3.11.7/lib/python3.11/site-packages/quacc/atoms/core.py", line 51, in get_atoms_id
    return hashlib.md5(encoded_atoms.encode("utf-8")).hexdigest()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
```

and script for reference

```python
from ase.build import bulk
from quacc.recipes.emt.core import relax_job

# Make an Atoms object of a bulk Cu structure
atoms = bulk("Cu")

# Run a structure relaxation on the Atoms object
result = relax_job(atoms)
print(result)
```

An easy workaround is to pass the `usedforsecurity = False` argument to md5(). I am unaware of the downstream consequences, but it will give your the correct output. Updated function in quacc/atoms/core.py below

```python
 def get_atoms_id(atoms: Atoms) -> str:
    """
    Returns a unique ID for the Atoms object. Note: The .info dict and calculator is
    excluded from the hash generation.

    Parameters
    ----------
    atoms
        Atoms object

    Returns
    -------
    str
        MD5 hash of the Atoms object
    """
    atoms = copy_atoms(atoms)
    atoms.info = {}
    atoms.calc = None
    encoded_atoms = encode(atoms)
    # This is a hack to avoid int32/int64 and float32/float64 differences
    # between machines.
    encoded_atoms = (
        encoded_atoms.replace("int64", "int")
        .replace("int32", "int")
        .replace("float64", "float")
        .replace("float32", "float")
    )

    return hashlib.md5(encoded_atoms.encode("utf-8"), usedforsecurity=False).hexdigest()
```

Where the only line that changes is line 51 in the file (the return argument in the function). I hope this helps.

**Comment by Andrew-S-Rosen** [comment]
Thank you very much for this helpful and detailed report, @wladerer! I was not previously aware of this. Good to know.

I have no reservations about implementing this workaround. After all, I would not recommend using `get_atoms_id` in any sort of security context. 😉 

It looks like the tests are bout to pass as-is in #2258, so I consider that sufficiently non-breaking. I'll mint a new release momentarily.
